### PR TITLE
fix Gitter badge URL

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
Another friendly bump =)

**Comment by yannickmathey** [comment]
Sorry for the late delay, thanks for the quick fix!

**Comment by DanielRuf** [comment]
You are welcome. Thanks for providing your time and the invested work.

**Pull request merged**
